### PR TITLE
Add youtube link in the footer - #273

### LINKED ISSUE #273: add links to YouTube playlist in the footer
## Type of Change
- [x] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
Currently there are icon links in the footer to my various social sites, and would like to add one for YouTube.
Screen Shot 2022-06-06 at 09 02 50

## Details
As I have grouped a few of my videos from the _About_ page into a playlist on YouTube, it might be good to add a logo there for YT that can link to the playlist. - https://youtube.com/playlist?list=PLRGBdE7KCzCfav_C807DsKaydedc6qq13

### PR DESCRIPTION
**Pull request by yacinec**
## Related Issue
Resolves #273

## Summary of Changes
I added the Youtube link in the footer including an svg icon. 

1. [x] Footer updated

### CODE REVIEW

**Review by thescientist13 — COMMENTED** [review]
Wow, thank you so much for this @yacinec, and from the deploy preview it looks great! 🙌

Will enable GitHub Actions for this in a moment (it might require a change to the footer spec which should be easy to make), but only request at the moment would be if the formatting changes here could be reverted. It looks like there may be some auto-formatting that converted single quotes to double quotes, added spacing / line breaks, etc and so would be nice to keep the changeset here clean and just focused on the immediate changes needed for implementing this feature itself.

Again, thanks again so much for this and if you feel like joining my [Slack community](https://join.slack.com/t/thegreenhouseio/shared_invite/enQtMzcyMzE2Mjk1MjgwLTU5YmM1MDJiMTg0ODk4MjA4NzUwNWFmZmMxNDY5MTcwM2I0MjYxN2VhOTEwNDU2YWQwOWQzZmY1YzY4MWRlOGI), around this and my main OSS [ProjectEvergreen](https://github.com/ProjectEvergreen) project, which is where Greenwood comes from (the site builder I use for this website), feel free to come join and say Hi!

**Comment by yacinec** [comment]
> Wow, thank you so much for this @yacinec, and from the deploy preview it looks great! 🙌
> 
> Will enable GitHub Actions for this in a moment (it might require a change to the footer spec which should be easy to make), but only request at the moment would be if the formatting changes here could be reverted. It looks like there may be some auto-formatting that converted single quotes to double quotes, added spacing / line breaks, etc and so would be nice to keep the changeset here clean and just focused on the immediate changes needed for implementing this feature itself.
> 
> Again, thanks again so much for this and if you feel like joining my [Slack community](https://join.slack.com/t/thegreenhouseio/shared_invite/enQtMzcyMzE2Mjk1MjgwLTU5YmM1MDJiMTg0ODk4MjA4NzUwNWFmZmMxNDY5MTcwM2I0MjYxN2VhOTEwNDU2YWQwOWQzZmY1YzY4MWRlOGI), around this and my main OSS project [ProjectEvergreen](https://github.com/ProjectEvergreen), which is where [**Greenwood**](https://www.greenwoodjs.io) comes from (the site builder I use for this website), feel free to come join and say Hi!

Hello @thescientist13, I'm sorry I've forgot to disable my VS Code auto indent. I'll remove the formatting!

**Review by thescientist13 — COMMENTED** [review]
Great, thanks for making that formatting change @yacinec all looks good to me!  💯 

As I thought, there might be a couple tests that would [need updating](https://github.com/thegreenhouseio/www.thegreenhouse.io/runs/6792946825?check_suite_focus=true), but it should be pretty easy.
```sh
2022-06-08T11:58:06.8491841Z Chrome: |███                           | 0/10 test files | 0 passed, 0 failed
2022-06-08T11:58:06.8497074Z 
2022-06-08T11:58:06.8498510Z Running tests...
2022-06-08T11:58:06.8498806Z 
2022-06-08T11:58:06.8499074Z Running 10 test files...
2022-06-08T11:58:06.8499398Z 
2022-06-08T11:58:06.8499604Z 
2022-06-08T11:58:14.5260658Z [2K[1A[2K[Gsrc/components/footer/footer.spec.js:
2022-06-08T11:58:14.5260898Z 
2022-06-08T11:58:14.5298260Z  ❌ Footer Component > Default Behavior > should have four <app-social-icon-link/> components in a list
2022-06-08T11:58:14.5298725Z       AssertionError: expected 5 to equal 4
2022-06-08T11:58:14.5299042Z       + expected - actual
2022-06-08T11:58:14.5299343Z       
2022-06-08T11:58:14.5299565Z       -5
2022-06-08T11:58:14.5299748Z       +4
2022-06-08T11:58:14.5299944Z       
2022-06-08T11:58:14.5300290Z       at Py.<anonymous> (src/components/footer/footer.spec.js:27:87)
2022-06-08T11:58:14.5300612Z 
2022-06-08T11:58:14.5300762Z 
2022-06-08T11:58:16.1466976Z [2K[1A[2K[Gsrc/services/social-links/social-links-service.spec.js:
2022-06-08T11:58:16.1467668Z 
2022-06-08T11:58:16.1470400Z  ❌ SocialLinksService > getLinks (default) > should have 4 links
2022-06-08T11:58:16.1473784Z       AssertionError: expected 5 to equal 4
2022-06-08T11:58:16.1474660Z       + expected - actual
2022-06-08T11:58:16.1475334Z       
2022-06-08T11:58:16.1475752Z       -5
2022-06-08T11:58:16.1475958Z       +4
2022-06-08T11:58:16.1476137Z       
2022-06-08T11:58:16.1476664Z       at o.<anonymous> (src/services/social-links/social-links-service.spec.js:23:31)
2022-06-08T11:58:16.1477046Z 
2022-06-08T11:58:16.1477569Z  ❌ SocialLinksService > getLinksAsArray > should be an array of four items
2022-06-08T11:58:16.1477964Z       AssertionError: expected 5 to equal 4
2022-06-08T11:58:16.1478284Z       + expected - actual
2022-06-08T11:58:16.1478487Z       
2022-06-08T11:58:16.1478698Z       -5
2022-06-08T11:58:16.1478892Z       +4
2022-06-08T11:58:16.1479069Z       
2022-06-08T11:58:16.1479533Z       at o.<anonymous> (src/services/social-links/social-links-service.spec.js:71:31)
2022-06-08T11:58:16.1480215Z 
2022-06-08T11:58:16.1480921Z Chrome: |██████████████████████████████| 10/10 test files | 52 passed, 3 failed, 1 skipped
2022-06-08T11:58:16.1481157Z 
2022-06-08T11:58:16.1481296Z Code coverage: 98.6 %
2022-06-08T11:58:16.1481768Z View full coverage report at reports/lcov-report/index.html
2022-06-08T11:58:16.1481973Z 
2022-06-08T11:58:16.1482186Z Finished running tests in 9.5s with 3 failed tests.
```

You'll just need to adjust the relevant `it` sections in the `Footer` and `SocialLinksServer` spec files (to account for the new link count) and then this is good to go!  🚀

**Comment by yacinec** [comment]
Thanks for your patience, I am not used to make open source contributions yet, I had not modified the tests. Now it should works : 

```
npm test

> www.thegreenhouse.io@3.2.0 test
> wtr


Chrome: |██████████████████████████████| 10/10 test files | 56 passed, 0 failed, 1 skipped

Code coverage: 98.6 %
View full coverage report at reports/lcov-report/index.html

Finished running tests in 1s, all tests passed! 🎉
```

I'm still available if something goes wrong.

**Pull request merged**
